name: Build And Publish Docker Image

on: 
   push: 
    branches: 
        - main
    
jobs:
    build_and_push_docker_image_to_docker_hub:
        name: Build and Push Docker Image to Docker Hub
        runs-on: ubuntu-latest
        steps:           
            - name: Extract Maven Project Version
              run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
              id: project
            
            - name: Log-In to Docker Hub
              uses: docker/login-action@v3.0.0
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
                logout: true
            
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3.1.0
              with:
                cleanup: true
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v5.1.0
              with:
                no-cache: true
                push: true
                context: ./tmr/
                file: ./Dockerfile
                target: serveprod
                tags: ${{secrets.DOCKER_USERNAME}}/task-manager-rest-api:${{ steps.project.outputs.version }}
            