name: CodeQL Analysis

on: 
    pull_request: 
        branches: 
            -"**"
    push:
        branches: 
            - "**"
    schedule:
      - cron: "0 0 * * *"

jobs:
  code_ql_analysis:
    name: CodeQL Analaysis

    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4.1.1
        
        - name: Initialize CodeQL
          uses: github/codeql-action/init@v3
          with:
            languages: 'java-kotlin'
        
        - name: Autobuild
          uses: github/codeql-action/autobuild@v3

        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v3
          with:
            category: "/language:java-kotlin"